### ISSUE TITLE
Have problem with dependencies, probably about 'adapters' package.

### ISSUE THREAD

**Issue by Changhao-Xiang** [ZUCC-AI/UMIE#1]
I ran this script
`bash -x scripts/test_eval.sh -p 1 -n 1 --task ie_multitask --model flan-t5 --ports 26768`
after pip install -r requirements.txt, but got following error:

/home/data_91_d/anaconda3/envs/xiangch-more/lib/python3.9/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "/home/nfs03/xiangch/UMIE/src/ie_multitask.py", line 2, in <module>
    from trainer_base import TrainerBase
  File "/home/nfs03/xiangch/UMIE/src/trainer_base.py", line 13, in <module>
    import modeling_t5
  File "/home/nfs03/xiangch/UMIE/src/modeling_t5.py", line 3, in <module>
    from my_transformers.modeling_t5 import (
  File "/home/nfs03/xiangch/UMIE/src/my_transformers/modeling_t5.py", line 50, in <module>
    from adapters import (
ImportError: cannot import name 'AdapterLayer' from 'adapters' (/home/data_91_d/anaconda3/envs/xiangch-more/lib/python3.9/site-packages/adapters/__init__.py)

also, I noticed that 'lora' and 'adapters' are not in requirements.txt, could you provide more infomation about the dependencies?

**Comment by qingyuannk** [comment]
"I'm sorry, 'lora' and 'adapters' are part of another experiment, and the code wasn't cleaned up during the upload. We have since updated the code. Thank you for your feedback."

**Comment by qingyuannk** [comment]
> I ran this script `bash -x scripts/test_eval.sh -p 1 -n 1 --task ie_multitask --model flan-t5 --ports 26768` after pip install -r requirements.txt, but got following error:
> 
> /home/data_91_d/anaconda3/envs/xiangch-more/lib/python3.9/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated and will be removed in future. Use torchrun. Note that --use_env is set by default in torchrun. If your script expects `--local_rank` argument to be set, please change it to read from `os.environ['LOCAL_RANK']` instead. See https://pytorch.org/docs/stable/distributed.html#launch-utility for further instructions
> 
> warnings.warn( Traceback (most recent call last): File "/home/nfs03/xiangch/UMIE/src/ie_multitask.py", line 2, in from trainer_base import TrainerBase File "/home/nfs03/xiangch/UMIE/src/trainer_base.py", line 13, in import modeling_t5 File "/home/nfs03/xiangch/UMIE/src/modeling_t5.py", line 3, in from my_transformers.modeling_t5 import ( File "/home/nfs03/xiangch/UMIE/src/my_transformers/modeling_t5.py", line 50, in from adapters import ( ImportError: cannot import name 'AdapterLayer' from 'adapters' (/home/data_91_d/anaconda3/envs/xiangch-more/lib/python3.9/site-packages/adapters/**init**.py)
> 
> also, I noticed that 'lora' and 'adapters' are not in requirements.txt, could you provide more infomation about the dependencies?

"I'm sorry, 'lora' and 'adapters' are part of another experiment, and the code wasn't cleaned up during the upload. We have since updated the code. Thank you for your feedback."

**Comment by qingyuannk** [comment]
> I ran this script `bash -x scripts/test_eval.sh -p 1 -n 1 --task ie_multitask --model flan-t5 --ports 26768` after pip install -r requirements.txt, but got following error:
> 
> /home/data_91_d/anaconda3/envs/xiangch-more/lib/python3.9/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated and will be removed in future. Use torchrun. Note that --use_env is set by default in torchrun. If your script expects `--local_rank` argument to be set, please change it to read from `os.environ['LOCAL_RANK']` instead. See https://pytorch.org/docs/stable/distributed.html#launch-utility for further instructions
> 
> warnings.warn( Traceback (most recent call last): File "/home/nfs03/xiangch/UMIE/src/ie_multitask.py", line 2, in from trainer_base import TrainerBase File "/home/nfs03/xiangch/UMIE/src/trainer_base.py", line 13, in import modeling_t5 File "/home/nfs03/xiangch/UMIE/src/modeling_t5.py", line 3, in from my_transformers.modeling_t5 import ( File "/home/nfs03/xiangch/UMIE/src/my_transformers/modeling_t5.py", line 50, in from adapters import ( ImportError: cannot import name 'AdapterLayer' from 'adapters' (/home/data_91_d/anaconda3/envs/xiangch-more/lib/python3.9/site-packages/adapters/**init**.py)
> 
> also, I noticed that 'lora' and 'adapters' are not in requirements.txt, could you provide more infomation about the dependencies?

I'm sorry, 'lora' and 'adapters' are part of another experiment, and the code wasn't cleaned up during the upload. We have since updated the code. Thank you for your feedback.

**Comment by Liar406** [comment]
I ran this script
bash -x scripts/test_eval.sh -p 1 -n 1 --task ie_multitask --model flan-t5 --ports 26768
after pip install -r requirements.txt, but got the same following error:


Traceback (most recent call last):
  File "/root/UMIE/src/ie_multitask.py", line 2, in <module>
    from trainer_base import TrainerBase
  File "/root/UMIE/src/trainer_base.py", line 15, in <module>
    from adapters import (
ImportError: cannot import name 'AdapterController' from 'adapters' (/root/miniconda3/envs/umie/lib/python3.9/site-packages/adapters/__init__.py)
