### ISSUE TITLE
 Some files that are not provided in this repository are needed

### ISSUE THREAD

**Issue by wyxscir** [ZUCC-AI/UMIE#2]
Thank you for the author's work! I would like to ask if it's possible to add some files to the code repository? For example, the 'run_data_generation.bash' file mentioned in the readme is missing, and there are also some schema files that are not present in the repository, such as '/home/data2/datasets/MNRE/record.schema

**Comment by qingyuannk** [comment]
> Thank you for the author's work! I would like to ask if it's possible to add some files to the code repository? For example, the 'run_data_generation.bash' file mentioned in the readme is missing, and there are also some schema files that are not present in the repository, such as '/home/data2/datasets/MNRE/record.schema

the bash scripts is here https://github.com/ZUCC-AI/UMIE/blob/main/text_processing/run_data_generation.bash and record.schema is generated   by processing data

**Comment by wyxscir** [comment]
> > Thank you for the author's work! I would like to ask if it's possible to add some files to the code repository? For example, the 'run_data_generation.bash' file mentioned in the readme is missing, and there are also some schema files that are not present in the repository, such as '/home/data2/datasets/MNRE/record.schema
> 
> the bash scripts is here https://github.com/ZUCC-AI/UMIE/blob/main/text_processing/run_data_generation.bash and record.schema is generated by processing data

Hi, I run this script, and there is another question. Running this needs a MNRE config, but there isn't a proper config in data_config/relation. Besides, in the load_from_file function in jointer.py, the parsing of JSON files needs the fields of spo_list, spo_details, and pos_tags which do not exist in the MNRE dataset, how could I get these fields?

**Comment by qingyuannk** [comment]
> > > Thank you for the author's work! I would like to ask if it's possible to add some files to the code repository? For example, the 'run_data_generation.bash' file mentioned in the readme is missing, and there are also some schema files that are not present in the repository, such as '/home/data2/datasets/MNRE/record.schema
> > 
> > 
> > the bash scripts is here https://github.com/ZUCC-AI/UMIE/blob/main/text_processing/run_data_generation.bash and record.schema is generated by processing data
> 
> Hi, I run this script, and there is another question. Running this needs a MNRE config, but there isn't a proper config in data_config/relation. Besides, in the load_from_file function in jointer.py, the parsing of JSON files needs the fields of spo_list, spo_details, and pos_tags which do not exist in the MNRE dataset, how could I get these fields?
The dataset processing config is updated!

**Comment by qingyuannk** [comment]
> > > Thank you for the author's work! I would like to ask if it's possible to add some files to the code repository? For example, the 'run_data_generation.bash' file mentioned in the readme is missing, and there are also some schema files that are not present in the repository, such as '/home/data2/datasets/MNRE/record.schema
> > 
> > 
> > the bash scripts is here https://github.com/ZUCC-AI/UMIE/blob/main/text_processing/run_data_generation.bash and record.schema is generated by processing data
> 
> Hi, I run this script, and there is another question. Running this needs a MNRE config, but there isn't a proper config in data_config/relation. Besides, in the load_from_file function in jointer.py, the parsing of JSON files needs the fields of spo_list, spo_details, and pos_tags which do not exist in the MNRE dataset, how could I get these fields?




the dataset processing config is updated in text_processing/data_config/!

**Comment by wyxscir** [comment]
> > > > Thank you for the author's work! I would like to ask if it's possible to add some files to the code repository? For example, the 'run_data_generation.bash' file mentioned in the readme is missing, and there are also some schema files that are not present in the repository, such as '/home/data2/datasets/MNRE/record.schema
> > > 
> > > 
> > > the bash scripts is here https://github.com/ZUCC-AI/UMIE/blob/main/text_processing/run_data_generation.bash and record.schema is generated by processing data
> > 
> > 
> > Hi, I run this script, and there is another question. Running this needs a MNRE config, but there isn't a proper config in data_config/relation. Besides, in the load_from_file function in jointer.py, the parsing of JSON files needs the fields of spo_list, spo_details, and pos_tags which do not exist in the MNRE dataset, how could I get these fields?
> 
> the dataset processing config is updated in text_processing/data_config/!

Thanks for your reply! I will try it as soon as possible. I wish you to be happy in Chinese New Year!
